"""Unified XTCE model module."""

from typing import Any

from ._base import XtceBaseModel
from .alarm import (
    Alarm,
    AlarmConditions,
    AlarmMultiRanges,
    AlarmRanges,
    BaseAlarm,
    BinaryAlarm,
    BinaryContextAlarm,
    BooleanAlarm,
    BooleanContextAlarm,
    ChangeAlarmRanges,
    CustomAlarm,
    EnumerationAlarm,
    EnumerationAlarmLevel,
    EnumerationContextAlarm,
    NumericAlarm,
    NumericContextAlarm,
    StringAlarm,
    StringAlarmLevel,
    StringContextAlarm,
    TimeAlarm,
    TimeAlarmRanges,
    TimeContextAlarm,
)
from .argument import (
    AbsoluteTimeArgument,
    AggregateArgument,
    ArrayArgument,
    BinaryArgument,
    BooleanArgument,
    EnumeratedArgument,
    FloatArgument,
    IntegerArgument,
    RelativeTimeArgument,
    StringArgument,
)
from .array import Dimension
from .codec import (
    BinaryDataEncoding,
    DataEncoding,
    DynamicValue,
    FloatDataEncoding,
    IntegerDataEncoding,
    LeadingSize,
    StringDataEncoding,
    TerminationCharacter,
    VariableString,
)
from .command import BlockMetaCommand, CommandMetadata, MetaCommand, MetaCommandRef
from .common import (
    Alias,
    AncillaryData,
    DescriptionBase,
    ExpandedNameReferenceNoPath,
    ExpandedNameReferenceWithPath,
    NameDescriptionBase,
    NameReferenceNoPath,
    NameReferenceWithPath,
    OptionalNameDescriptionBase,
)
from .container import (
    ArrayParameterRefEntry,
    BaseContainer,
    Container,
    ContainerBinaryDataEncoding,
    ContainerRefEntry,
    ContainerSegmentRefEntry,
    IndirectParameterRefEntry,
    LocationInContainer,
    ParameterRefEntry,
    ParameterSegmentRefEntry,
    RestrictionCriteria,
    SequenceContainer,
    SequenceEntry,
    StreamSegmentEntry,
)
from .datatype import (
    AbsoluteTimeData,
    AggregateData,
    ArrayData,
    BaseData,
    BinaryData,
    BooleanData,
    EnumeratedData,
    FloatData,
    IntegerData,
    RelativeTimeData,
    StringData,
    Unit,
)
from .enum import (
    Basis,
    BitOrder,
    ChangeBasis,
    ChangeSpan,
    ChecksumTypeName,
    ConcernLevel,
    Endian,
    FloatEncoding,
    IntegerEncoding,
    MathOperators,
    PcmType,
    RangeForm,
    ReferenceLocation,
    ReferencePoint,
    StringEncoding,
    SystemType,
    TelemetryDataSource,
    TimeUnits,
    UnitForm,
    ValidationStatus,
)
from .misc import Repeat
from .parameter import (
    AbsoluteTimeParameter,
    AggregateParameter,
    ArrayParameter,
    BinaryParameter,
    BooleanParameter,
    EnumeratedParameter,
    FloatParameter,
    IntegerParameter,
    Parameter,
    ParameterProperties,
    PhysicalAddress,
    RelativeTimeParameter,
    StringParameter,
)
from .processing import (
    CRC,
    XOR,
    BaseCalibrator,
    Calibrator,
    Checksum,
    ContextCalibrator,
    ContextMatch,
    DiscreteLookup,
    DiscreteLookupList,
    InputAlgorithm,
    InputOutputAlgorithm,
    InputOutputTriggerAlgorithm,
    LinearAdjustment,
    MatchCriteria,
    MathAlgorithm,
    Parity,
    SimpleAlgorithm,
    ThisParameterOperand,
    ValueOperand,
)
from .range import FloatRange, MultiRangeType
from .reference import (
    ContainerRef,
    ParameterInstanceRef,
    ParameterRef,
    ServiceRef,
)
from .space_system import (
    ContainerRef as SpaceSystemContainerRef,
)
from .space_system import (
    Header,
    MessageRef,
    Service,
    SpaceSystem,
)
from .stream import (
    CustomStream,
    FixedFrameStream,
    FrameStream,
    PcmStream,
    RateInStream,
    RateInStreamWithStreamName,
    VariableFrameStream,
)
from .telemetry import Message, MessageSet, TelemetryMetadata
from .time import TimeAssociation

__all__ = [
    "XtceBaseModel",
    "Alarm",
    "AlarmConditions",
    "AlarmMultiRanges",
    "AlarmRanges",
    "BaseAlarm",
    "BinaryAlarm",
    "BinaryContextAlarm",
    "BooleanAlarm",
    "BooleanContextAlarm",
    "ChangeAlarmRanges",
    "CustomAlarm",
    "EnumerationAlarm",
    "EnumerationAlarmLevel",
    "EnumerationContextAlarm",
    "NumericAlarm",
    "NumericContextAlarm",
    "StringAlarm",
    "StringAlarmLevel",
    "StringContextAlarm",
    "TimeAlarm",
    "TimeAlarmRanges",
    "TimeContextAlarm",
    "AbsoluteTimeArgument",
    "AggregateArgument",
    "ArrayArgument",
    "BinaryArgument",
    "BooleanArgument",
    "EnumeratedArgument",
    "FloatArgument",
    "IntegerArgument",
    "RelativeTimeArgument",
    "StringArgument",
    "Dimension",
    "BinaryDataEncoding",
    "DataEncoding",
    "DynamicValue",
    "FloatDataEncoding",
    "IntegerDataEncoding",
    "LeadingSize",
    "StringDataEncoding",
    "TerminationCharacter",
    "VariableString",
    "BlockMetaCommand",
    "CommandMetadata",
    "MetaCommand",
    "MetaCommandRef",
    "Alias",
    "AncillaryData",
    "DescriptionBase",
    "ExpandedNameReferenceNoPath",
    "ExpandedNameReferenceWithPath",
    "NameDescriptionBase",
    "NameReferenceNoPath",
    "NameReferenceWithPath",
    "OptionalNameDescriptionBase",
    "ArrayParameterRefEntry",
    "BaseContainer",
    "Container",
    "ContainerBinaryDataEncoding",
    "ContainerRefEntry",
    "ContainerSegmentRefEntry",
    "IndirectParameterRefEntry",
    "LocationInContainer",
    "ParameterRefEntry",
    "ParameterSegmentRefEntry",
    "RestrictionCriteria",
    "SequenceContainer",
    "SequenceEntry",
    "StreamSegmentEntry",
    "AbsoluteTimeData",
    "AggregateData",
    "ArrayData",
    "BaseData",
    "BinaryData",
    "BooleanData",
    "EnumeratedData",
    "FloatData",
    "IntegerData",
    "RelativeTimeData",
    "StringData",
    "Unit",
    "Basis",
    "BitOrder",
    "ChangeBasis",
    "ChangeSpan",
    "ChecksumTypeName",
    "ConcernLevel",
    "Endian",
    "FloatEncoding",
    "IntegerEncoding",
    "MathOperators",
    "PcmType",
    "RangeForm",
    "ReferenceLocation",
    "ReferencePoint",
    "StringEncoding",
    "SystemType",
    "TelemetryDataSource",
    "TimeUnits",
    "UnitForm",
    "ValidationStatus",
    "ContextMatch",
    "DiscreteLookup",
    "DiscreteLookupList",
    "MatchCriteria",
    "Repeat",
    "AbsoluteTimeParameter",
    "AggregateParameter",
    "ArrayParameter",
    "BinaryParameter",
    "BooleanParameter",
    "EnumeratedParameter",
    "FloatParameter",
    "IntegerParameter",
    "Parameter",
    "ParameterProperties",
    "PhysicalAddress",
    "RelativeTimeParameter",
    "StringParameter",
    "BaseCalibrator",
    "CRC",
    "Calibrator",
    "Checksum",
    "ContextCalibrator",
    "InputAlgorithm",
    "InputOutputAlgorithm",
    "InputOutputTriggerAlgorithm",
    "LinearAdjustment",
    "MathAlgorithm",
    "Parity",
    "SimpleAlgorithm",
    "ThisParameterOperand",
    "ValueOperand",
    "XOR",
    "FloatRange",
    "MultiRangeType",
    "ContainerRef",
    "ParameterInstanceRef",
    "ParameterRef",
    "ServiceRef",
    "SpaceSystemContainerRef",
    "Header",
    "MessageRef",
    "Service",
    "SpaceSystem",
    "CustomStream",
    "FixedFrameStream",
    "FrameStream",
    "PcmStream",
    "RateInStream",
    "RateInStreamWithStreamName",
    "VariableFrameStream",
    "Message",
    "MessageSet",
    "TelemetryMetadata",
    "TimeAssociation",
]


def _rebuild_all_models(
    base_class: type[XtceBaseModel], namespace: dict[str, Any]
) -> None:
    """Recursively find and rebuild all Pydantic models.

    This resolves forward references for all models in the module.
    """
    for subclass in base_class.__subclasses__():
        try:
            subclass.model_rebuild(_types_namespace=namespace)
            _rebuild_all_models(subclass, namespace)
        except Exception as e:
            raise RuntimeError(
                f"Error rebuilding model {subclass.__name__}: {e}"
            ) from e


_rebuild_all_models(XtceBaseModel, globals())
