"""Unified XTCE model module."""

from .arguments import (
    AbsoluteTimeArgument,
    AggregateArgument,
    ArrayArgument,
    BinaryArgument,
    BooleanArgument,
    EnumeratedArgument,
    FloatArgument,
    IntegerArgument,
    RelativeTimeArgument,
    StringArgument,
)
from .codec import (
    BinaryDataEncoding,
    DataEncoding,
    FloatDataEncoding,
    IntegerDataEncoding,
    StringDataEncoding,
)
from .commands import CommandMetadata
from .common import (
    Alias,
    AncillaryData,
)
from .datatypes import BaseData, IntegerData
from .enums import (
    BitOrder,
    Endian,
    FloatEncoding,
    IntegerEncoding,
    StringEncoding,
    SystemType,
    UnitForm,
    ValidationStatus,
)
from .match import DiscreteLookup, MatchCriteria
from .parameters import (
    AbsoluteTimeParameter,
    AggregateParameter,
    ArrayParameter,
    BinaryParameter,
    BooleanParameter,
    EnumeratedParameter,
    FloatParameter,
    IntegerParameter,
    Parameter,
    ParameterInstance,
    ParameterRef,
    RelativeTimeParameter,
    StringParameter,
)
from .processing import (
    CRC,
    XOR,
    BaseCalibrator,
    Calibrator,
    Checksum,
    ContextCalibrator,
    InputAlgorithm,
    InputOutputTriggerAlgorithm,
    LinearAdjustment,
    MathAlgorithm,
    Parity,
    SimpleAlgorithm,
)
from .space_system import SpaceSystem
from .stream import CustomStream, FixedFrameStream, VariableFrameStream
from .telemetry import TelemetryMetadata

__all__ = [
    "AbsoluteTimeArgument",
    "AggregateArgument",
    "ArrayArgument",
    "BinaryArgument",
    "BooleanArgument",
    "EnumeratedArgument",
    "FloatArgument",
    "IntegerArgument",
    "RelativeTimeArgument",
    "StringArgument",
    "BinaryDataEncoding",
    "DataEncoding",
    "FloatDataEncoding",
    "IntegerDataEncoding",
    "StringDataEncoding",
    "CommandMetadata",
    "Alias",
    "AncillaryData",
    "BaseData",
    "IntegerData",
    "BitOrder",
    "Endian",
    "FloatEncoding",
    "IntegerEncoding",
    "StringEncoding",
    "SystemType",
    "UnitForm",
    "ValidationStatus",
    "DiscreteLookup",
    "MatchCriteria",
    "AbsoluteTimeParameter",
    "AggregateParameter",
    "ArrayParameter",
    "BinaryParameter",
    "BooleanParameter",
    "EnumeratedParameter",
    "FloatParameter",
    "IntegerParameter",
    "Parameter",
    "ParameterInstance",
    "ParameterRef",
    "RelativeTimeParameter",
    "StringParameter",
    "CRC",
    "XOR",
    "BaseCalibrator",
    "Calibrator",
    "Checksum",
    "ContextCalibrator",
    "InputAlgorithm",
    "InputOutputTriggerAlgorithm",
    "LinearAdjustment",
    "MathAlgorithm",
    "Parity",
    "SimpleAlgorithm",
    "SpaceSystem",
    "CustomStream",
    "FixedFrameStream",
    "VariableFrameStream",
    "TelemetryMetadata",
]
